# Generated by Django 6.0 on 2025-12-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mliner_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlinershortner',
            old_name='original_link',
            new_name='original_url',
        ),
    ]
